# -*- encoding: utf-8 -*-
##############################################################################
#
# ERP Heritage
# Copyright (C) 2026 (https://www.erpheritage.com.au/)
#
##############################################################################
"""
Shared test base for AP automation.

Sets up:

* Default tolerance profile (loaded by data file).
* A vendor (partner_a from base) with a purchase journal in scope.
* Two products with default codes used by the regex parser.
* A purchase order with two confirmed lines and a fully received
  delivery ready for 3 way match tests.
"""

from odoo.addons.eh_account_base.tests.common import EhAccountIntegrationTestCase


class EhApTestCase(EhAccountIntegrationTestCase):

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

        cls.purchase_journal = cls.env['account.journal'].search([
            ('type', '=', 'purchase'),
            ('company_id', '=', cls.company.id),
        ], limit=1)
        if not cls.purchase_journal:
            cls.purchase_journal = cls.env['account.journal'].create({
                'name': 'Vendor Bills',
                'code': 'BILL',
                'type': 'purchase',
                'company_id': cls.company.id,
            })

        Product = cls.env['product.product']
        cls.product_a = Product.create({
            'name': 'Test Widget',
            'default_code': 'WIDGET-001',
            'type': 'consu',
            'standard_price': 10.0,
            'list_price': 15.0,
        })
        cls.product_b = Product.create({
            'name': 'Test Gadget',
            'default_code': 'GADGET-002',
            'type': 'consu',
            'standard_price': 20.0,
            'list_price': 30.0,
        })

        cls.default_profile = cls.env['eh.ap.tolerance.profile'].search([
            ('is_default', '=', True),
            ('company_id', '=', cls.company.id),
        ], limit=1)
        if not cls.default_profile:
            cls.default_profile = cls.env['eh.ap.tolerance.profile'].create({
                'name': 'Test Default',
                'is_default': True,
                'qty_tolerance_pct': 2.0,
                'price_tolerance_pct': 1.0,
                'amount_tolerance': 5.0,
                'over_receipt_pct': 0.0,
            })

    @classmethod
    def _create_purchase_order(cls, lines):
        """Create and confirm a purchase order.

        :param lines: list of (product, qty, price) tuples.
        :return: the confirmed purchase.order record.
        """
        po_line_vals = []
        for product, qty, price in lines:
            po_line_vals.append((0, 0, {
                'product_id': product.id,
                'name': product.display_name,
                'product_qty': qty,
                'price_unit': price,
                'product_uom': product.uom_id.id,
            }))
        po = cls.env['purchase.order'].create({
            'partner_id': cls.partner_a.id,
            'company_id': cls.company.id,
            'order_line': po_line_vals,
        })
        po.button_confirm()
        return po

    @classmethod
    def _confirm_receipt(cls, purchase_order, qty_overrides=None):
        """Validate the incoming picking generated by the PO.

        :param qty_overrides: optional dict {po_line_id: qty} to set
            received qty per line.
        """
        qty_overrides = qty_overrides or {}
        picking = purchase_order.picking_ids[:1]
        if not picking:
            return picking
        for move in picking.move_ids:
            po_line = move.purchase_line_id
            qty = qty_overrides.get(po_line.id, move.product_uom_qty)
            # stock.move.quantity_done was renamed to quantity (with a
            # separate picked flag) in Odoo 17.
            if 'quantity' in move._fields:
                move.quantity = qty
                move.picked = True
            else:
                move.quantity_done = qty
        res = picking.button_validate()
        # A partial receipt prompts a backorder-confirmation wizard on some
        # series (the validate returns the wizard action instead of
        # finalising). Process it so the received quantity is committed and
        # qty_received reflects the partial receipt.
        if isinstance(res, dict) and res.get('res_model') == \
                'stock.backorder.confirmation':
            ctx = dict(res.get('context') or {})
            wizard = cls.env['stock.backorder.confirmation'].with_context(
                ctx).create({'pick_ids': [(6, 0, picking.ids)]})
            wizard.process()
        return picking
